image: andthensome/docker-node-rsync

pipelines:
  branches:
    develop:
      - step:
          name: "Build Package"
          image: andthensome/docker-node-rsync
          artifacts:
            - pipeline/**
          caches:
            - node
          script:
            - echo "Build Package... 🙌"
            - "npm install"
            - "npm run build -- --production --pipeline"
      - step:
          name: "Deploy to UAT"
          image: andthensome/docker-node-rsync
          trigger: manual
          deployment: staging
          script:
            - echo "Deploying to UAT... 🙌"
            - "rsync -rvz -e 'ssh' pipeline/ $THEME_DIR"
    master:
      - step:
          name: "Build Package"
          image: andthensome/docker-node-rsync
          artifacts:
            - pipeline/**
          caches:
            - node
          script:
            - echo "Build Package... 🙌"
            #- 'npm config set "//npm.fontawesome.com/:_authToken" D6D771B4-20F4-4BF3-91DA-9DD21FC3300E'
            - "npm install"
            - "npm run build -- --production --pipeline"
#      - step:
#          name: "Deploy to UAT"
#          image: andthensome/docker-node-rsync
#          trigger: automatic
#          deployment: staging
#          script:
#            - echo "Deploying to UAT... 🙌"
#            - "rsync --ignore-times -rvz -e 'ssh' pipeline/ $THEME_DIR"
      - step:
          name: "Deploy to Production"
          image: andthensome/docker-node-rsync
          trigger: manual
          deployment: production
          script:
            - echo "Build Package... 🙌"
            - echo "Deploying to Production... 😬"
            - "rsync --ignore-times -rvz -e 'ssh -p 18765' pipeline/ $THEME_DIR"
