<?php

$labels = array(
	'name'                  => _x( 'Forms', 'Post Type General Name'),
	'singular_name'         => _x( 'Form', 'Post Type Singular Name'),
	'menu_name'             => __( 'Forms'),
	'name_admin_bar'        => __( 'Form'),
	'archives'              => __( 'Form Archives'),
	'attributes'            => __( 'Form Attributes'),
	'parent_item_colon'     => __( 'Parent Form:'),
	'all_items'             => __( 'All Forms'),
	'add_new_item'          => __( 'Add New Form'),
	'add_new'               => __( 'Add New'),
	'new_item'              => __( 'New Form'),
	'edit_item'             => __( 'Edit Form'),
	'update_item'           => __( 'Update Form'),
	'view_item'             => __( 'View Form'),
	'view_items'            => __( 'View Forms'),
	'search_items'          => __( 'Search Form'),
	'not_found'             => __( 'Not found'),
	'not_found_in_trash'    => __( 'Not found in Trash'),
	'featured_image'        => __( 'Featured Image'),
	'set_featured_image'    => __( 'Set featured image'),
	'remove_featured_image' => __( 'Remove featured image'),
	'use_featured_image'    => __( 'Use as featured image'),
	'insert_into_item'      => __( 'Insert into form'),
	'uploaded_to_this_item' => __( 'Uploaded to this form'),
	'items_list'            => __( 'Forms list'),
	'items_list_navigation' => __( 'Forms list navigation'),
	'filter_items_list'     => __( 'Filter forms list'),
);
$args = array(
	'label'                 => __( 'Form'),
	'description'           => __( 'Forms'),
	'labels'                => $labels,
	'supports'              => array( 'title', 'revisions' ),
	'hierarchical'          => false,
	'public'                => true,
	'show_ui'               => true,
	'show_in_menu'          => true,
	'menu_position'         => 5,
	'menu_icon'             => 'dashicons-welcome-write-blog',
	'show_in_admin_bar'     => true,
	'show_in_nav_menus'     => false,
	'can_export'            => true,
	'has_archive'           => false,
	'exclude_from_search'   => true,
	'publicly_queryable'    => true,
	'rewrite'               => false,
	'capability_type'       => 'page',
	'show_in_rest'          => true,
);
register_post_type( 'form', $args );
