<?php

$labels = array(
    'name'                  => _x( 'Truths', 'Post Type General Name', 'text_domain' ),
    'singular_name'         => _x( 'Truth', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'             => __( 'Truths', 'text_domain' ),
    'name_admin_bar'        => __( 'Truth', 'text_domain' ),
    'archives'              => __( 'Truth Archives', 'text_domain' ),
    'attributes'            => __( 'Truth Attributes', 'text_domain' ),
    'parent_item_colon'     => __( 'Parent Truth:', 'text_domain' ),
    'all_items'             => __( 'All Truths', 'text_domain' ),
    'add_new_item'          => __( 'Add New Truth', 'text_domain' ),
    'add_new'               => __( 'Add New', 'text_domain' ),
    'new_item'              => __( 'New Truth', 'text_domain' ),
    'edit_item'             => __( 'Edit Truth', 'text_domain' ),
    'update_item'           => __( 'Update Truth', 'text_domain' ),
    'view_item'             => __( 'View Truth', 'text_domain' ),
    'view_items'            => __( 'View Truths', 'text_domain' ),
    'search_items'          => __( 'Search Truth', 'text_domain' ),
    'not_found'             => __( 'Not found', 'text_domain' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
    'featured_image'        => __( 'Featured Image', 'text_domain' ),
    'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
    'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
    'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
    'insert_into_item'      => __( 'Insert into truth', 'text_domain' ),
    'uploaded_to_this_item' => __( 'Uploaded to this truth', 'text_domain' ),
    'items_list'            => __( 'Truths list', 'text_domain' ),
    'items_list_navigation' => __( 'Truths list navigation', 'text_domain' ),
    'filter_items_list'     => __( 'Filter truths list', 'text_domain' ),
);
$args = array(
    'label'                 => __( 'Truth', 'text_domain' ),
    'description'           => __( 'Truths', 'text_domain' ),
    'labels'                => $labels,
    'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions' ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'menu_icon'             => 'dashicons-megaphone',
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => false,
    'can_export'            => true,
    'has_archive'           => true,
    'exclude_from_search'   => true,
    'publicly_queryable'    => false,
    'capability_type'       => 'post',
    'show_in_rest'          => false,
);
register_post_type( 'truth', $args );
